"""
Emit real LaTeX figure and table environments.

Until now the manuscript typeset its captions as a list and included no images
and no tabulars at all: PaperA.pdf carried zero embedded images. The captions
described floats that were not there.

This reads the same numbering map that `assemble_manuscript.py` owns, so figures
and tables cannot drift out of step with it, and writes:

    tex/figures.tex   figure environments with \\includegraphics
    tex/tables.tex    the committed CSVs as booktabs tabulars

Tables are typeset from the CSVs rather than transcribed, so a number can only
be wrong in the table if it is wrong in the pipeline that produced it.
"""
import csv
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from assemble_manuscript import FIGURES, TABLES, final_name       # noqa: E402

NUMBERED = ROOT / "outputs" / "manuscript"
TEX = ROOT / "manuscript" / "tex"

# LaTeX-safe: these arrive from CSV headers and cell values, not from prose.
ESC = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_"}

# CSV headers are machine names chosen for the analysis scripts. Typesetting them
# raw gives a preprint with "mu_per_yr" and "breakeven_eta" in its tables, so the
# column names are mapped once, here, rather than renamed in the CSVs -- those are
# the published numbers and their headers are referenced by the test suite.
HEADER = {
    "c": r"$c$ (y)", "theta": r"$\theta$ (y$^{-1}$)", "r": "$r$",
    "computed_x1e3": r"computed ($\times10^{-3}$)",
    "published_x1e3": r"published ($\times10^{-3}$)", "diff": "difference",
    "mu_per_yr": r"$\mu$ (y$^{-1}$)", "omega_ratio": r"$\Omega_\mu/\Omega_{T^*}$",
    "r_star": r"$r^\star$", "crosses": r"$r^\star>1$",
    "mixture": "stratification", "cancellation": r"$\hat\lambda/\lambda_E$",
    "eta0_with_mu": r"$\eta=0$, with $\mu$", "eta1_with_mu": r"$\eta=1$, with $\mu$",
    "subtype": "subtype", "vl_threshold": "VL threshold (copies/mL)",
    "mdri_days": "MDRI (d)", "shadow_days": "shadow (d)", "participants": "participants",
    "case": "case", "truth": "truth", "naive": "naive",
    "wang_reweighted": "reweighted", "naive_bias": "naive bias",
    "wang_bias": "reweighted bias", "pct_removed": "bias removed (\\%)",
    "eta": r"$\eta$", "site": "site county", "q_J": "$q_J$", "q_P": "$q_P$",
    "r_eta0": r"$r^\star$ at $\eta=0$", "r_eta0.25": r"$r^\star$ at $\eta=0.25$",
    "r_eta0.5": r"$r^\star$ at $\eta=0.5$", "breakeven_eta": r"break-even $\eta$",
    "inter_test_model": "inter-test model", "P0": "$P_0$",
    "r_star_min": r"$r^\star$ min", "r_star_max": r"$r^\star$ max",
    "spread": "spread", "relative_spread": "relative spread",
    "invariance": "invariance",
}


def esc(x: str) -> str:
    x = str(x).strip()
    if x.startswith("$") and x.endswith("$"):        # already math
        return x
    # bare LaTeX in a cell (e.g. "$\eta=0$") is left alone; plain text is escaped
    if "\\" in x or "$" in x:
        return x
    return "".join(ESC.get(c, c) for c in x)


def order(labels):
    """Main text first, then supplement, each in numeric order."""
    def key(l):
        m = re.search(r"(S?)(\d+)([a-z]?)", l)
        return (m.group(1) == "S", int(m.group(2)), m.group(3))
    return sorted(labels, key=key)


def figures_tex() -> str:
    out = ["% Generated by analysis/build_floats.py. Do not edit.", ""]
    for label in order(FIGURES):
        stem = final_name(label)
        src = NUMBERED / f"{stem}.pdf"
        if not src.exists():
            print(f"  skipping {label}: {src.name} absent")
            continue
        cap = FIGURES[label][2]
        # bare filename: \graphicspath in the preamble resolves it both in the
        # repository build and in a flat submission bundle where the figures sit
        # beside the .tex
        out += [r"\begin{figure}[htbp]", r"  \centering",
                rf"  \includegraphics[width=\textwidth]{{{src.name}}}",
                rf"  \caption*{{\textbf{{{label}.}} {cap}}}",
                rf"  \label{{fig:{stem}}}",
                r"\end{figure}", ""]
    return "\n".join(out)


def tables_tex() -> str:
    out = ["% Generated by analysis/build_floats.py. Do not edit.", ""]
    for label in order(TABLES):
        stem = final_name(label)
        src = NUMBERED / f"{stem}.csv"
        if not src.exists():
            print(f"  skipping {label}: {src.name} absent")
            continue
        rows = [r for r in csv.reader(src.open()) if r]
        head, body = rows[0], rows[1:]
        ncol = len(head)
        spec = "l" + "r" * (ncol - 1)
        cap = TABLES[label][2]
        out += [r"\begin{table}[htbp]", r"  \centering", r"  \small",
                rf"  \caption*{{\textbf{{{label}.}} {cap}}}",
                rf"  \label{{tab:{stem}}}",
                rf"  \begin{{tabular}}{{{spec}}}", r"    \toprule",
                "    " + " & ".join(HEADER.get(h, esc(h)) for h in head) + r" \\",
                r"    \midrule"]
        for r in body:
            r = (r + [""] * ncol)[:ncol]
            out.append("    " + " & ".join(esc(c) for c in r) + r" \\")
        out += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
    return "\n".join(out)


def environments() -> dict:
    """
    {label: LaTeX environment}, for injection at the point of first citation.

    Floats collected at the end of a document force the reader to leaf back and
    forth; a figure belongs next to the sentence that argues from it. build_tex.py
    places each of these after the paragraph that first cites it.
    """
    out = {}
    for label in order(FIGURES):
        stem = final_name(label)
        src = NUMBERED / f"{stem}.pdf"
        if not src.exists():
            continue
        out[label] = "\n".join([
            r"\begin{figure}[htbp]", r"  \centering",
            rf"  \includegraphics[width=\textwidth]{{{src.name}}}",
            rf"  \caption*{{\textbf{{{label}.}} {FIGURES[label][2]}}}",
            rf"  \label{{fig:{stem}}}", r"\end{figure}", ""])
    for label in order(TABLES):
        stem = final_name(label)
        src = NUMBERED / f"{stem}.csv"
        if not src.exists():
            continue
        rows = [r for r in csv.reader(src.open()) if r]
        head, body = rows[0], rows[1:]
        ncol = len(head)
        lines = [r"\begin{table}[htbp]", r"  \centering", r"  \small",
                 rf"  \caption*{{\textbf{{{label}.}} {TABLES[label][2]}}}",
                 rf"  \label{{tab:{stem}}}",
                 rf"  \begin{{tabular}}{{{'l' + 'r' * (ncol - 1)}}}",
                 r"    \toprule",
                 "    " + " & ".join(HEADER.get(h, esc(h)) for h in head) + r" \\",
                 r"    \midrule"]
        for r in body:
            r = (r + [""] * ncol)[:ncol]
            lines.append("    " + " & ".join(esc(c) for c in r) + r" \\")
        lines += [r"    \bottomrule", r"  \end{tabular}", r"\end{table}", ""]
        out[label] = "\n".join(lines)
    return out


def main():
    env = environments()
    figs = sum(1 for k in env if k.startswith("Figure"))
    print(f"  {figs} figure and {len(env) - figs} table environments available")
    print("  placed inline by build_tex.py at first citation")
    return 0


if __name__ == "__main__":
    sys.exit(main())
